### ISSUE TITLE
Suggestion: rename `ctr` to `rctr` for avoiding name conflict

### ISSUE THREAD

**Issue by AkihiroSuda** [ktock/remote-snapshotter#12]

**Comment by AkihiroSuda** [comment]
imgcrypt has `ctr-enc` command: https://github.com/containerd/imgcrypt

If we follow that convention, maybe the name should be like `ctr-remote`, but I don't have a strong opinion about the name as long as it doesn't conflict with existing commands.

**Comment by ktock** [comment]
Thanks a lot for your suggestion! `imgcrypt` style (= renaming `ctr` to `ctr-remote`) sounds good to me.
